server:
  port: 8080
spring:
  application:
    name: openbank-transactions-app
  datasource:
    url: jdbc:h2:mem:transactions
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
      enabled: true
  security:
    basic:
      enabled: false
    filter:
      enabled: false
    user:
      name: sa
      password: sa
  management:
    endpoints:
      web:
        exposure:
          include:
            - "*"
openbank:
  sandbox:
    url: https://apisandbox.openbankproject.com/obp/v1.2.1/
